# **Homework - Session 1**

## **Import libs**

In [29]:
import numpy as np
import pandas as pd

### **Question 1**

What's the version of NumPy that you installed? 

You can get the version information using the `__version__` field:

In [30]:
np.__version__

'1.21.2'

### **Question 2**

What's the version of Pandas? 

In [31]:
pd.__version__

'1.3.2'

### **Getting the data** 

For this homework, we'll use the same dataset as for the next session - the car price dataset.

Download it from [here](https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv).

And read it with Pandas

In [32]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

In [33]:
data.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

### **Question 3**

What's the average price of BMW cars in the dataset?

In [127]:
df_full_1 = data.copy()

In [130]:
df_bmw = df_full_1[df_full_1.Make == "BMW"]

In [131]:
df_bmw.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [132]:
df_bmw.MSRP.mean()

61546.76347305389

## **Question 4**

Select a subset of cars after year 2015. How many of them have missing values for Engine HP?

In [133]:
df_after_2015 = data[data.Year >= 2015] # (including 2015) 

In [134]:
df_after_2015.head(2)

Make       Model  Year                Engine Fuel Type  Engine HP  \
32  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   

    Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32               4.0            MANUAL  rear wheel drive              2.0   
33               4.0            MANUAL  rear wheel drive              2.0   

   Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
32     Performance      Compact   Convertible           35        26   
33     Performance      Compact   Convertible           35        26   

    Popularity   MSRP  
32         819  27495  
33         819  24995

In [135]:
df_after_2015["Engine HP"].isnull().sum()

51

### **Question 5**

* Calculate the average "Engine HP" in the dataset. 
* Use the `fillna` method and to fill the missing values in "Engine HP" with the mean value from the previous step. 
* Now, calcualte the average of "Engine HP" again.
* Has it changed? 

Round both means before answering this questions. You can use the `round` function for that:

```python
print(round(mean_hp_before))
print(round(mean_hp_after))
```

In [136]:
# AVG of "Engine HP"
mean_hp_before = round(df_full_1["Engine HP"].mean())
mean_hp_before

249

In [137]:
# NaN values in "Engine HP"
df_full_1["Engine HP"].isnull().sum()

69

In [138]:
# Fill missing values in "Engine HP"
df_full_1["Engine HP"].fillna(mean_hp_before, inplace=True)

In [139]:
# NaN values in "Engine HP"
df_full_1["Engine HP"].isnull().sum()

0

In [140]:
# AVG of "Engine HP"
mean_hp_after = round(data["Engine HP"].mean())
mean_hp_after

249

_**the average of "Engine HP" hasn't changed**_

### **Question 6**

* Select all the "Rolls-Royce" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
* Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 7 rows).
* Get the underlying NumPy array. Let's call it `X`.
* Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
* Invert `XTX`.
* What's the sum of all the elements of the result?

In [141]:
df_full_2 = df_full_1.copy()

In [142]:
df_full_2.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [143]:
df_rolls_royce = df_full_2[df_full_2.Make == "Rolls-Royce"]

In [145]:
df_rolls_royce = df_rolls_royce[["Engine HP", "Engine Cylinders", "highway MPG"]]

In [146]:
df_rolls_royce.head(2)

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19

In [147]:
df_rolls_royce.duplicated().sum()

24

In [148]:
df_rolls_royce.drop_duplicates(inplace=True)

In [149]:
df_rolls_royce.shape

(7, 3)

In [150]:
# Get the underlying NumPy array. Let's call it X
X = df_rolls_royce.values

In [151]:
type(X)

numpy.ndarray

In [152]:
# Compute matrix-matrix multiplication between the transpose of X and X
# To get the transpose, use X.T 
# Let's call the result XTX

X_T = X.T
XTX = X_T.dot(X)

In [153]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [154]:
# Invert XTX
XTX_inv = np.linalg.inv(XTX)

In [155]:
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [156]:
# What's the sum of all the elements of the result?
XTX_inv.sum()

0.032212320677486125

### **Questions 7** 

* Create an array `y` with values `[1000, 1100, 900, 1200, 1000, 850, 1300]`.
* Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
* What's the value of the first element of `w`?.

In [157]:
# Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300]
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [160]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. 
# Call the result w.

w_temp = XTX_inv.dot(X.T)
w  = w_temp.dot(y)

In [161]:
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [162]:
# What's the value of the first element of w?
w[0]

0.19989598183188972